name: confapp
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  meta: ^1.9.1
  synchronized: ^3.1.0
  rohd:
    path: /home/yquek/home/workspace/rohd-hcl/doc/rohd
  rohd_hcl:
    path: /home/yquek/home/workspace/rohd-hcl

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0