#!/usr/bin/env bash
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

mode="${1:-}"
overrides="pubspec_overrides.yaml"
source_state=".confapp_dependency_sources"
marker="# Generated by tool/confapp_dev_mode.sh. Do not edit by hand."
default_rohd_path="$HOME/max/rohd"
default_viewer_path="$HOME/true-release/rohd-schematic-viewer"

rohd_git_url="${ROHD_GIT_URL:-https://github.com/intel/rohd.git}"
rohd_git_ref="${ROHD_GIT_REF:-main}"
viewer_git_url="${SCHEMATIC_VIEWER_GIT_URL:-https://github.com/intel/rohd-schematic-viewer.git}"
viewer_git_ref="${SCHEMATIC_VIEWER_GIT_REF:-main}"

usage() {
  cat <<'USAGE'
Usage: tool/confapp_dev_mode.sh <mode>

Configure individual package sources:
  tool/confapp_dev_mode.sh configure <package> <source> ...
  where each source is hosted, git, or local.

For example:
  tool/confapp_dev_mode.sh configure \
    rohd_schematic_viewer local \
    rohd_source_navigator local

Modes:
  manifest      Disable overrides and use pubspec.yaml sources.
  local-rohd    Use the local ROHD checkout and its split packages.
  local-viewer  Use the local schematic-viewer checkout.
  local-all     Use local ROHD packages and the local schematic viewer.
  show          Print the current generated override file, if present.
  configure-group  Configure a dependency group while preserving other sources.

Supported packages:
  rohd
  rohd_hierarchy
  rohd_devtools_widgets
  rohd_source_navigator
  rohd_schematic_viewer

The default local checkouts are ~/max/rohd and
~/true-release/rohd-schematic-viewer. Override them with ROHD_LOCAL_PATH and
SCHEMATIC_VIEWER_LOCAL_PATH.

Git sources use ROHD_GIT_URL, ROHD_GIT_REF, SCHEMATIC_VIEWER_GIT_URL, and
SCHEMATIC_VIEWER_GIT_REF. Hosted sources use the constraints in pubspec.yaml.

With no overrides, pubspec.yaml supplies the hosted release dependencies.
USAGE
}

ensure_managed_or_absent() {
  if [[ -f "$overrides" ]] && ! grep -qxF "$marker" "$overrides"; then
    echo "$overrides exists and was not generated by tool/confapp_dev_mode.sh." >&2
    echo "Move or remove it before switching development modes." >&2
    exit 1
  fi
}

backup_overrides() {
  local backup="$overrides.disabled"
  local suffix=1

  if [[ ! -f "$overrides" ]]; then
    echo "No $overrides present; using dependencies from pubspec.yaml."
    return
  fi

  while [[ -e "$backup" ]]; do
    backup="$overrides.disabled.$suffix"
    suffix=$((suffix + 1))
  done

  mv -- "$overrides" "$backup"
  echo "Moved $overrides to $backup; using dependencies from pubspec.yaml."
}

expand_home_path() {
  local path="$1"

  case "$path" in
    '~') printf '%s\n' "$HOME" ;;
    \~/*) printf '%s/%s\n' "$HOME" "${path:2}" ;;
    *) printf '%s\n' "$path" ;;
  esac
}

resolve_rohd_path() {
  local rohd_path="${ROHD_LOCAL_PATH:-$default_rohd_path}"

  rohd_path="$(expand_home_path "$rohd_path")"
  [[ "$rohd_path" = /* ]] || rohd_path="$repo_root/$rohd_path"
  if [[ ! -f "$rohd_path/pubspec.yaml" ]] ||
    ! grep -Eq '^name:[[:space:]]*rohd[[:space:]]*$' "$rohd_path/pubspec.yaml"; then
    echo "Could not find a ROHD checkout at $rohd_path." >&2
    echo "Set ROHD_LOCAL_PATH to a checkout rooted at the rohd package." >&2
    exit 1
  fi

  realpath "$rohd_path"
}

resolve_rohd_package_path() {
  local package="$1"
  local rohd_path
  local package_path

  rohd_path="$(resolve_rohd_path)"
  if [[ "$package" == "rohd" ]]; then
    package_path="$rohd_path"
  else
    package_path="$rohd_path/packages/$package"
  fi

  if [[ ! -f "$package_path/pubspec.yaml" ]] ||
    ! grep -Eq "^name:[[:space:]]*$package[[:space:]]*$" "$package_path/pubspec.yaml"; then
    echo "Missing local ROHD package: $package_path" >&2
    exit 1
  fi

  realpath "$package_path"
}

resolve_viewer_path() {
  local viewer_path="${SCHEMATIC_VIEWER_LOCAL_PATH:-${ROHD_SCHEMATIC_VIEWER_PATH:-$default_viewer_path}}"

  viewer_path="$(expand_home_path "$viewer_path")"
  [[ "$viewer_path" = /* ]] || viewer_path="$repo_root/$viewer_path"
  if [[ ! -f "$viewer_path/pubspec.yaml" ]] ||
    ! grep -Eq '^name:[[:space:]]*rohd_schematic_viewer[[:space:]]*$' "$viewer_path/pubspec.yaml"; then
    echo "Could not find a schematic-viewer checkout at $viewer_path." >&2
    echo "Set SCHEMATIC_VIEWER_LOCAL_PATH to the package checkout." >&2
    exit 1
  fi

  realpath "$viewer_path"
}

validate_package() {
  case "$1" in
    rohd|rohd_hierarchy|rohd_devtools_widgets|rohd_source_navigator|rohd_schematic_viewer) ;;
    *)
      echo "Unsupported package '$1'." >&2
      echo "Run '$0 help' to see the supported packages." >&2
      exit 2
      ;;
  esac
}

validate_source() {
  local package="$1"
  local source="$2"

  case "$source" in
    hosted|git|local) ;;
    *)
      echo "Invalid dependency source '$source'; expected hosted, git, or local." >&2
      exit 2
      ;;
  esac

}

append_git_dependency() {
  local output="$1"
  local package="$2"
  local url="$rohd_git_url"
  local ref="$rohd_git_ref"
  local path=""

  case "$package" in
    rohd) ;;
    rohd_hierarchy|rohd_devtools_widgets|rohd_source_navigator)
      path="packages/$package"
      ;;
    rohd_schematic_viewer)
      url="$viewer_git_url"
      ref="$viewer_git_ref"
      ;;
  esac

  cat >>"$output" <<YAML
  $package:
    git:
      url: $url
      ref: $ref
YAML
  if [[ -n "$path" ]]; then
    printf '      path: %s\n' "$path" >>"$output"
  fi
}

append_local_dependency() {
  local output="$1"
  local package="$2"
  local package_path

  if [[ "$package" == "rohd_schematic_viewer" ]]; then
    package_path="$(resolve_viewer_path)"
  else
    package_path="$(resolve_rohd_package_path "$package")"
  fi

  printf '  %s:\n    path: %s\n' "$package" "$package_path" >>"$output"
}

write_configured_overrides() {
  local args=("$@")
  local package
  local source
  local output
  local index
  local has_overrides=false
  local -A seen_packages=()

  if [[ "${#args[@]}" -eq 0 || "$(( ${#args[@]} % 2 ))" -ne 0 ]]; then
    echo "Usage: $0 configure <package> <hosted|git|local> ..." >&2
    exit 2
  fi

  for ((index = 0; index < ${#args[@]}; index += 2)); do
    package="${args[index]}"
    source="${args[index + 1]}"
    validate_package "$package"
    validate_source "$package" "$source"
    if [[ -n "${seen_packages[$package]:-}" ]]; then
      echo "Package '$package' was configured more than once." >&2
      exit 2
    fi
    seen_packages["$package"]=1

    if [[ "$source" == "local" ]]; then
      if [[ "$package" == "rohd_schematic_viewer" ]]; then
        resolve_viewer_path >/dev/null
      else
        resolve_rohd_package_path "$package" >/dev/null
      fi
    fi
  done

  ensure_managed_or_absent
  output="$(mktemp "${TMPDIR:-/tmp}/rohd-hcl-overrides.XXXXXX")"
  trap 'rm -f "$output"' EXIT
  cat >"$output" <<YAML
$marker
# This file is intentionally ignored by Git.
dependency_overrides:
YAML

  for ((index = 0; index < ${#args[@]}; index += 2)); do
    package="${args[index]}"
    source="${args[index + 1]}"
    case "$source" in
      hosted) ;;
      git)
        append_git_dependency "$output" "$package"
        has_overrides=true
        ;;
      local)
        append_local_dependency "$output" "$package"
        has_overrides=true
        ;;
    esac
  done

  if [[ "$has_overrides" == false ]]; then
    rm -f -- "$output"
    trap - EXIT
    rm -f -- "$overrides"
    echo "All configured dependencies use pubspec.yaml; no override file is needed."
    return
  fi

  mv -- "$output" "$overrides"
  trap - EXIT
  echo "Wrote $overrides with individually configured package sources."
}

write_source_state() {
  cat >"$source_state" <<STATE
rohd=$1
rohd_hierarchy=$2
rohd_devtools_widgets=$3
rohd_source_navigator=$4
rohd_schematic_viewer=$5
STATE
}

write_group_configuration() {
  local group="${1:-}"
  local source="${2:-}"
  local rohd_source="hosted"
  local hierarchy_source="hosted"
  local widgets_source="hosted"
  local navigator_source="hosted"
  local viewer_source="hosted"
  local package
  local saved_source

  if [[ "$#" -ne 2 ]]; then
    echo "Usage: $0 configure-group <rohd|package|widget|schematic|all> <source>" >&2
    exit 2
  fi

  if [[ -f "$source_state" ]]; then
    while IFS='=' read -r package saved_source; do
      case "$package" in
        rohd) rohd_source="$saved_source" ;;
        rohd_hierarchy) hierarchy_source="$saved_source" ;;
        rohd_devtools_widgets) widgets_source="$saved_source" ;;
        rohd_source_navigator) navigator_source="$saved_source" ;;
        rohd_schematic_viewer) viewer_source="$saved_source" ;;
      esac
    done <"$source_state"
  fi

  case "$group" in
    rohd)
      validate_source rohd "$source"
      rohd_source="$source"
      ;;
    package)
      validate_source rohd_hierarchy "$source"
      hierarchy_source="$source"
      navigator_source="$source"
      ;;
    widget)
      validate_source rohd_devtools_widgets "$source"
      hierarchy_source="$source"
      widgets_source="$source"
      navigator_source="$source"
      ;;
    schematic)
      validate_source rohd_schematic_viewer "$source"
      viewer_source="$source"
      ;;
    all)
      validate_source rohd "$source"
      rohd_source="$source"
      hierarchy_source="$source"
      widgets_source="$source"
      navigator_source="$source"
      ;;
    *)
      echo "Invalid dependency group '$group'; expected rohd, package, widget, schematic, or all." >&2
      exit 2
      ;;
  esac

  write_configured_overrides \
    rohd "$rohd_source" \
    rohd_hierarchy "$hierarchy_source" \
    rohd_devtools_widgets "$widgets_source" \
    rohd_source_navigator "$navigator_source" \
    rohd_schematic_viewer "$viewer_source"
  write_source_state \
    "$rohd_source" \
    "$hierarchy_source" \
    "$widgets_source" \
    "$navigator_source" \
    "$viewer_source"
}

use_manifest_dependencies() {
  ensure_managed_or_absent
  backup_overrides
  rm -f -- "$source_state"
}

use_local_rohd_dependencies() {
  write_group_configuration all local
}

use_local_viewer_dependency() {
  write_group_configuration schematic local
}

use_all_local_dependencies() {
  write_group_configuration all local
  write_group_configuration schematic local
}

case "$mode" in
  configure)
    shift
    write_configured_overrides "$@"
    ;;
  configure-group) write_group_configuration "${2:-}" "${3:-}" ;;
  manifest) use_manifest_dependencies ;;
  local-rohd) use_local_rohd_dependencies ;;
  local-viewer) use_local_viewer_dependency ;;
  local-all) use_all_local_dependencies ;;
  show)
    if [[ -f "$overrides" ]]; then
      cat "$overrides"
    else
      echo "No $overrides present; using dependencies from pubspec.yaml."
    fi
    ;;
  hp-hv)
    echo "Mode hp-hv is deprecated; use manifest." >&2
    use_manifest_dependencies
    ;;
  lp-hv)
    echo "Mode lp-hv is deprecated; use local-rohd." >&2
    use_local_rohd_dependencies
    ;;
  hp-lv)
    echo "Mode hp-lv is deprecated; use local-viewer." >&2
    use_local_viewer_dependency
    ;;
  lp-lv)
    echo "Mode lp-lv is deprecated; use local-all." >&2
    use_all_local_dependencies
    ;;
  -h|--help|help|"") usage ;;
  *) usage >&2; exit 2 ;;
esac
